services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres_csharp
    environment:
      POSTGRES_DB: prueba_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
